import { Suspense } from 'react'
import type { Metadata } from 'next'
import { Environment } from '@/config/environment'
import TanstackQueryContext from '@/contexts/TanstackQueryContext'
import ThemeProviderContext from '@/contexts/ThemeProviderContext'
import { initMockApi } from '@/lib/msw/initMockApi'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: '나비장터',
  description: 'Generated by create next app',
}

if (Environment.apiMocking() === 'enabled') {
  console.log('Mocking enabled')
  initMockApi()
}

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <TanstackQueryContext>
          <ThemeProviderContext>
            <Suspense>
              {children}
              {authModal}
            </Suspense>
          </ThemeProviderContext>
        </TanstackQueryContext>
      </body>
    </html>
  )
}
